sudo: required
dist: xenial
language: python
virtualenv:
  system_site_packages: true
python:
- '3.5'
install:
- python3 setup.py build
- python3 setup.py install
script:
- cd python/example && python3 example.py 
